### PR TITLE
Update main.css

### PR DESCRIPTION
**Pull request by evil-tmetz**

### CODE REVIEW

**Review by tmetz — CHANGES_REQUESTED** [review]
I request changes!

**Review by tmetz2 — CHANGES_REQUESTED** [review]
change all the things

**Review by tmetz — APPROVED** [review]
fine

**Review by tmetz — APPROVED** [review]

**Review by tmetz2 — APPROVED** [review]

**Review by tmetz — CHANGES_REQUESTED** [review]
I request changes!

**Pull request merged**
